/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "TREDT_Gaming2009",
    "x": -1360.66292452882,
    "z": 6570.430440784068
  }
{
    "name": ".SoumyaDas4971",
    "x": 133.7000000000000,
    "z": 2,644.86000000000
  }
{
    "name": ".TamerSolid17662",
    "x": -2848.38,
    "z": 1581.63
  }
  {
    "name": ".TREDTGaming10 2",
    "x": 141.39,
    "z": 2805.39
  }
  {
    "name": "SuperSon3AA",
    "x": 845.09,
    "z": 4536.45
  }
  {
    "name": "SDDas2",
    "x": 15.50,
    "z": 2602.50
  }
  {
    "name": "Soumya_Tredt2009",
    "x": 0.50,
    "z": 0.50
  }
  {
    "name": "SamSuperUltraMax",
    "x": 224.70,
    "z": 2657.92
  }
  {
    "name": "Ishaan_Tredt",
    "x": -59.50,
    "z": 2765.75
  }
  {
    "name": "IshaanMC",
    "x": 17.50,
    "z": 2603.50
  }
     {
    "name": "Ishaan_2011",
    "x": -329.59,
    "z": 2455.39
  }
     {
    "name": "HemangChugh",
    "x": 726.06,
    "z": 4510.38
  }
      {
    "name": "Anshuman",
    "x": 123.24,
    "z": 2614.52
  }
     {
    "name": ".TREDTgaming2010",
    "x": 85.28,
    "z": 2686.09
  }
   ]
